# Generated by Django 4.2.24 on 2025-09-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/pdfs/'),
        ),
    ]
